import type { ModuleKey } from "@/types/sector";

type ModuleMeta = {
  labelKey: string;
  icon: string;
  route: string;
};

const moduleKeys: ModuleKey[] = [
  "dashboard",
  "clients",
  "crm",
  "ventes",
  "produits",
  "stock",
  "devis",
  "facturation",
  "paiements",
  "fournisseurs",
  "finances",
  "comptabilite",
  "rh",
  "rapports",
  "assistant",
  "ai-sales-agent",
  "ai-studio",
  "support",
  "gouvernance",
  "utilisateurs",
  "roles-permissions",
  "notifications",
  "documents",
  "statistiques",
  "commandes",
  "reservations",
  "menus",
  "cuisine",
  "recettes",
  "achats",
  "chantiers",
  "contrats",
  "materiels",
  "materiaux",
  "budgets",
  "patients",
  "medecins",
  "rendez-vous",
  "consultations",
  "pharmacie",
  "laboratoire",
  "dossiers-medicaux",
  "etudiants",
  "enseignants",
  "classes",
  "emploi-du-temps",
  "examens",
  "cours",
  "presences",
  "frais-scolaires",
  "flotte",
  "conducteurs",
  "expeditions",
  "itineraires",
  "carburant",
  "maintenance",
  "production",
  "matieres-premieres",
  "machines",
  "ordres-fabrication",
  "chambres",
  "housekeeping",
  "restaurant-hotel",
  "proprietes",
  "unites",
  "disponibilites",
  "nettoyage",
  "appartements",
  "locataires",
  "loyers",
  "depots",
  "services",
  "activites",
  "check-in",
  "parcelles",
  "cultures",
  "intrants",
  "recoltes",
  "traitements",
  "animaux",
  "production-lait",
  "alimentation",
  "soins",
  "lots",
  "ponte",
  "reproduction",
  "parametres",
];

const icons: Partial<Record<ModuleKey, string>> = {
  dashboard: "grid-outline",
  clients: "people-outline",
  crm: "briefcase-outline",
  ventes: "cart-outline",
  produits: "pricetags-outline",
  stock: "cube-outline",
  devis: "document-outline",
  facturation: "receipt-outline",
  paiements: "card-outline",
  fournisseurs: "business-outline",
  finances: "cash-outline",
  comptabilite: "calculator-outline",
  rh: "id-card-outline",
  rapports: "bar-chart-outline",
  assistant: "sparkles-outline",
  "ai-sales-agent": "chatbubbles-outline",
  "ai-studio": "color-wand-outline",
  support: "help-buoy-outline",
  gouvernance: "shield-checkmark-outline",
  utilisateurs: "people-circle-outline",
  "roles-permissions": "key-outline",
  notifications: "notifications-outline",
  documents: "folder-outline",
  statistiques: "analytics-outline",
  commandes: "bag-handle-outline",
  reservations: "calendar-outline",
  menus: "restaurant-outline",
  cuisine: "flame-outline",
  recettes: "book-outline",
  achats: "basket-outline",
  chantiers: "hammer-outline",
  contrats: "reader-outline",
  materiels: "construct-outline",
  materiaux: "cube-outline",
  budgets: "wallet-outline",
  patients: "medical-outline",
  medecins: "medkit-outline",
  "rendez-vous": "calendar-number-outline",
  consultations: "clipboard-outline",
  pharmacie: "bandage-outline",
  laboratoire: "flask-outline",
  "dossiers-medicaux": "folder-open-outline",
  etudiants: "school-outline",
  enseignants: "person-outline",
  classes: "library-outline",
  "emploi-du-temps": "time-outline",
  examens: "create-outline",
  cours: "book-outline",
  presences: "checkmark-done-outline",
  "frais-scolaires": "cash-outline",
  flotte: "bus-outline",
  conducteurs: "person-circle-outline",
  expeditions: "send-outline",
  itineraires: "map-outline",
  carburant: "speedometer-outline",
  maintenance: "build-outline",
  production: "cog-outline",
  "matieres-premieres": "layers-outline",
  machines: "hardware-chip-outline",
  "ordres-fabrication": "list-outline",
  chambres: "bed-outline",
  housekeeping: "sparkles-outline",
  "restaurant-hotel": "restaurant-outline",
  proprietes: "business-outline",
  unites: "key-outline",
  disponibilites: "calendar-outline",
  nettoyage: "sparkles-outline",
  appartements: "home-outline",
  locataires: "people-outline",
  loyers: "cash-outline",
  depots: "wallet-outline",
  services: "briefcase-outline",
  activites: "ticket-outline",
  "check-in": "log-in-outline",
  parcelles: "map-outline",
  cultures: "leaf-outline",
  intrants: "flask-outline",
  recoltes: "basket-outline",
  traitements: "medkit-outline",
  animaux: "paw-outline",
  "production-lait": "water-outline",
  alimentation: "nutrition-outline",
  soins: "heart-outline",
  lots: "albums-outline",
  ponte: "egg-outline",
  reproduction: "git-branch-outline",
  parametres: "settings-outline",
};

const routes: Partial<Record<ModuleKey, string>> = {
  dashboard: "/",
  clients: "/module/crm",
  crm: "/module/crm",
  ventes: "/module/ventes",
  commandes: "/module/ventes",
  produits: "/module/stock",
  stock: "/module/stock",
  facturation: "/module/facturation",
  devis: "/module/facturation",
  "frais-scolaires": "/module/facturation",
  finances: "/module/comptabilite",
  comptabilite: "/module/comptabilite",
  rh: "/module/rh",
  presences: "/module/rh",
  rapports: "/module/rapports",
  statistiques: "/module/rapports",
  reservations: "/module/rendez-vous",
  "rendez-vous": "/module/rendez-vous",
  production: "/module/production",
  "ordres-fabrication": "/module/production",
  "matieres-premieres": "/module/stock",
};

export const moduleMeta: Record<ModuleKey, ModuleMeta> = moduleKeys.reduce(
  (acc, key) => {
    acc[key] = {
      labelKey: `nav.${key}`,
      icon: icons[key] ?? "apps-outline",
      route: routes[key] ?? `/module/${key}`,
    };
    return acc;
  },
  {} as Record<ModuleKey, ModuleMeta>,
);
