import type { ModuleKey, SectorDefinition, SectorKey } from "@/types/sector";

const commonModules: ModuleKey[] = [
  "rapports",
  "assistant",
  "parametres",
  "utilisateurs",
  "roles-permissions",
  "notifications",
  "documents",
  "statistiques",
  "support",
  "ai-sales-agent",
  "ai-studio",
];

function defineSector(input: SectorDefinition): SectorDefinition {
  return input;
}

export const sectors: Record<SectorKey, SectorDefinition> = {
  general: defineSector({
    key: "general",
    labelKey: "sector.general",
    descriptionKey: "sector.description.general",
    icon: "business-outline",
    accent: "#00A889",
    modules: [
      "dashboard",
      "clients",
      "crm",
      "ventes",
      "produits",
      "stock",
      "devis",
      "facturation",
      "paiements",
      "fournisseurs",
      "finances",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "revenue", labelKey: "kpi.revenue", value: "482 300 EUR", trendKey: "trend.month" },
      { key: "customers", labelKey: "kpi.customers", value: "1 208", trendKey: "trend.month" },
      { key: "tasks", labelKey: "kpi.priorityTasks", value: "18", trendKey: "trend.today" },
    ],
    priorityActionKeys: ["action.lateInvoices", "action.quotesToFollow", "action.pendingUsers"],
    recentActivityKeys: ["activity.customerCreated", "activity.invoicePaid", "activity.reportGenerated"],
  }),
  restaurant: defineSector({
    key: "restaurant",
    labelKey: "sector.restaurant",
    descriptionKey: "sector.description.restaurant",
    icon: "restaurant-outline",
    accent: "#FF6B00",
    modules: [
      "dashboard",
      "clients",
      "commandes",
      "reservations",
      "menus",
      "cuisine",
      "recettes",
      "stock",
      "achats",
      "facturation",
      "paiements",
      "finances",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "sales", labelKey: "kpi.dailySales", value: "4 280 EUR", trendKey: "trend.today" },
      { key: "orders", labelKey: "kpi.orders", value: "186", trendKey: "trend.live" },
      { key: "stock", labelKey: "kpi.kitchenStock", value: "7", trendKey: "trend.urgent" },
    ],
    priorityActionKeys: ["action.confirmReservations", "action.kitchenRestock", "action.reviewFoodCost"],
    recentActivityKeys: ["activity.tableClosed", "activity.reservationConfirmed", "activity.kitchenAlertResolved"],
  }),
  commerce: defineSector({
    key: "commerce",
    labelKey: "sector.commerce",
    descriptionKey: "sector.description.commerce",
    icon: "storefront-outline",
    accent: "#2563EB",
    modules: [
      "dashboard",
      "clients",
      "produits",
      "ventes",
      "commandes",
      "stock",
      "fournisseurs",
      "paiements",
      "facturation",
      "finances",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "sales", labelKey: "kpi.sales", value: "128 450 EUR", trendKey: "trend.month" },
      { key: "transactions", labelKey: "kpi.transactions", value: "342", trendKey: "trend.month" },
      { key: "stock", labelKey: "kpi.criticalStock", value: "12", trendKey: "trend.action" },
    ],
    priorityActionKeys: ["action.restockBestSellers", "action.openReturns", "action.reconcileCash"],
    recentActivityKeys: ["activity.posSale", "activity.productUpdated", "activity.supplierDelivery"],
  }),
  construction: defineSector({
    key: "construction",
    labelKey: "sector.construction",
    descriptionKey: "sector.description.construction",
    icon: "hammer-outline",
    accent: "#CA8A04",
    modules: [
      "dashboard",
      "clients",
      "chantiers",
      "devis",
      "contrats",
      "materiels",
      "materiaux",
      "fournisseurs",
      "achats",
      "budgets",
      "facturation",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "projects", labelKey: "kpi.activeProjects", value: "9", trendKey: "trend.priority" },
      { key: "budget", labelKey: "kpi.committedBudget", value: "1.24 M EUR", trendKey: "trend.budget" },
      { key: "materials", labelKey: "kpi.criticalMaterials", value: "5", trendKey: "trend.order" },
    ],
    priorityActionKeys: ["action.siteReports", "action.orderMaterials", "action.budgetVariance"],
    recentActivityKeys: ["activity.sitePhoto", "activity.budgetUpdated", "activity.contractSigned"],
  }),
  sante: defineSector({
    key: "sante",
    labelKey: "sector.sante",
    descriptionKey: "sector.description.sante",
    icon: "medkit-outline",
    accent: "#0891B2",
    modules: [
      "dashboard",
      "patients",
      "medecins",
      "rendez-vous",
      "consultations",
      "pharmacie",
      "laboratoire",
      "dossiers-medicaux",
      "facturation",
      "paiements",
      "finances",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "patients", labelKey: "kpi.patients", value: "642", trendKey: "trend.month" },
      { key: "appointments", labelKey: "kpi.appointments", value: "186", trendKey: "trend.today" },
      { key: "billing", labelKey: "kpi.toBill", value: "68 400 EUR", trendKey: "trend.follow" },
    ],
    priorityActionKeys: ["action.confirmAppointments", "action.completePatientFiles", "action.sendMutualInvoices"],
    recentActivityKeys: ["activity.consultationAdded", "activity.paymentRecorded", "activity.prescriptionPrepared"],
  }),
  education: defineSector({
    key: "education",
    labelKey: "sector.education",
    descriptionKey: "sector.description.education",
    icon: "school-outline",
    accent: "#7C3AED",
    modules: [
      "dashboard",
      "etudiants",
      "enseignants",
      "classes",
      "emploi-du-temps",
      "examens",
      "cours",
      "presences",
      "frais-scolaires",
      "facturation",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "students", labelKey: "kpi.students", value: "1 280", trendKey: "trend.month" },
      { key: "fees", labelKey: "kpi.unpaidFees", value: "27", trendKey: "trend.follow" },
      { key: "attendance", labelKey: "kpi.absences", value: "37", trendKey: "trend.watch" },
    ],
    priorityActionKeys: ["action.unpaidFees", "action.unusualAbsences", "action.publishSchedules"],
    recentActivityKeys: ["activity.studentRegistered", "activity.teacherAssigned", "activity.examPlanned"],
  }),
  transport: defineSector({
    key: "transport",
    labelKey: "sector.transport",
    descriptionKey: "sector.description.transport",
    icon: "bus-outline",
    accent: "#0284C7",
    modules: [
      "dashboard",
      "clients",
      "flotte",
      "conducteurs",
      "expeditions",
      "itineraires",
      "carburant",
      "maintenance",
      "facturation",
      "paiements",
      "finances",
      ...commonModules,
    ],
    kpis: [
      { key: "shipments", labelKey: "kpi.shipments", value: "148", trendKey: "trend.month" },
      { key: "fleet", labelKey: "kpi.activeVehicles", value: "36", trendKey: "trend.live" },
      { key: "maintenance", labelKey: "kpi.maintenance", value: "5", trendKey: "trend.plan" },
    ],
    priorityActionKeys: ["action.delayedShipments", "action.vehicleMaintenance", "action.deliveryProofs"],
    recentActivityKeys: ["activity.routeCompleted", "activity.fuelEntry", "activity.driverCheckIn"],
  }),
  industrie: defineSector({
    key: "industrie",
    labelKey: "sector.industrie",
    descriptionKey: "sector.description.industrie",
    icon: "construct-outline",
    accent: "#9333EA",
    modules: [
      "dashboard",
      "clients",
      "production",
      "matieres-premieres",
      "machines",
      "achats",
      "stock",
      "fournisseurs",
      "ordres-fabrication",
      "facturation",
      "finances",
      "rh",
      ...commonModules,
    ],
    kpis: [
      { key: "production", labelKey: "kpi.production", value: "94%", trendKey: "trend.month" },
      { key: "machines", labelKey: "kpi.machines", value: "18", trendKey: "trend.online" },
      { key: "raw", labelKey: "kpi.rawMaterials", value: "9", trendKey: "trend.low" },
    ],
    priorityActionKeys: ["action.productionOrders", "action.rawMaterials", "action.machineMaintenance"],
    recentActivityKeys: ["activity.productionClosed", "activity.machineInspected", "activity.stockAdjusted"],
  }),
  hotel: defineSector({
    key: "hotel",
    labelKey: "sector.hotel",
    descriptionKey: "sector.description.hotel",
    icon: "bed-outline",
    accent: "#DB2777",
    modules: [
      "dashboard",
      "reservations",
      "chambres",
      "clients",
      "housekeeping",
      "restaurant-hotel",
      "facturation",
      "paiements",
      "rh",
      "finances",
      ...commonModules,
    ],
    kpis: [
      { key: "occupancy", labelKey: "kpi.occupancy", value: "78%", trendKey: "trend.month" },
      { key: "rooms", labelKey: "kpi.rooms", value: "42", trendKey: "trend.booked" },
      { key: "payments", labelKey: "kpi.payments", value: "18 200 EUR", trendKey: "trend.month" },
    ],
    priorityActionKeys: ["action.confirmArrivals", "action.assignHousekeeping", "action.closeInvoices"],
    recentActivityKeys: ["activity.guestCheckedIn", "activity.roomCleaned", "activity.bookingPaid"],
  }),
};

export const sectorList = Object.values(sectors);
