export const rhKpis = [
  { label: "Employes", value: "48" },
  { label: "Presents", value: "42" },
  { label: "Conges", value: "6" },
  { label: "Masse salariale", value: "186 400 EUR" },
];

export const employees = [
  {
    name: "Amina Diallo",
    role: "Sales manager",
    contract: "CDI",
    status: "Present",
    email: "amina.diallo@enterpriseerp.com",
    phone: "+46 70 110 22 33",
    department: "Sales",
    manager: "Ladifa Makouet",
    startDate: "2023-03-14",
    salary: "4 200 EUR",
    leaveBalance: "18 days",
    documents: "Contract, ID, payroll",
    nextAction: "Review quarterly objectives",
  },
  {
    name: "Lucas Martin",
    role: "Accountant",
    contract: "CDI",
    status: "Leave",
    email: "lucas.martin@enterpriseerp.com",
    phone: "+46 70 330 44 55",
    department: "Finance",
    manager: "Ladifa Makouet",
    startDate: "2022-09-01",
    salary: "4 450 EUR",
    leaveBalance: "6 days",
    documents: "Contract, certifications",
    nextAction: "Validate accounting export rights",
  },
  {
    name: "Sara Lindstrom",
    role: "Customer support",
    contract: "CDD",
    status: "Present",
    email: "sara.lindstrom@enterpriseerp.com",
    phone: "+46 70 660 77 88",
    department: "Support",
    manager: "Amina Diallo",
    startDate: "2024-01-08",
    salary: "3 650 EUR",
    leaveBalance: "12 days",
    documents: "Contract, onboarding file",
    nextAction: "Assign customer onboarding queue",
  },
];
