export const navigationItems = [
  { name: "Accueil Cloud", href: "/" },
  { name: "Dashboard", href: "/dashboard" },
  { name: "Solutions", href: "/solutions" },
  { name: "Pricing", href: "/pricing" },
  { name: "Demo", href: "/demo" },
  { name: "ROI", href: "/roi" },
  { name: "Clients", href: "/customers" },
  { name: "CRM", href: "/crm" },
  { name: "Ventes", href: "/ventes" },
  { name: "Stock", href: "/stock" },
  { name: "Facturation", href: "/facturation" },
  { name: "Comptabilite", href: "/comptabilite" },
  { name: "RH", href: "/rh" },
  { name: "Assistant IA", href: "/assistant" },
  { name: "Integrations", href: "/integrations" },
  { name: "Securite", href: "/security" },
  { name: "Status", href: "/status" },
  { name: "FAQ", href: "/faq" },
  { name: "Onboarding", href: "/onboarding" },
  { name: "Parametres", href: "/parametres" },
];
