export const enterpriseRoles = [
  "SUPER_ADMIN",
  "OWNER",
  "ADMINISTRATOR",
  "MANAGER",
  "SALES",
  "ACCOUNTING",
  "INVENTORY",
  "HR",
  "EMPLOYEE",
  "VIEWER",
] as const;

export const enterprisePermissions = [
  "company.read",
  "company.update",
  "users.read",
  "users.invite",
  "users.update",
  "roles.manage",
  "crm.read",
  "crm.create",
  "crm.update",
  "crm.delete",
  "sales.read",
  "sales.create",
  "invoice.read",
  "invoice.create",
  "invoice.validate",
  "invoice.cancel",
  "stock.read",
  "stock.adjust",
  "stock.transfer",
  "finance.read",
  "finance.export",
  "hr.read",
  "hr.manage",
  "projects.read",
  "projects.manage",
  "ai.use",
  "reports.read",
  "settings.manage",
  "audit.read",
] as const;

export type EnterpriseRole = (typeof enterpriseRoles)[number];
export type EnterprisePermission = (typeof enterprisePermissions)[number];

export const rolePermissions: Record<EnterpriseRole, EnterprisePermission[]> = {
  SUPER_ADMIN: [...enterprisePermissions],
  OWNER: [...enterprisePermissions],
  ADMINISTRATOR: enterprisePermissions.filter((permission) => permission !== "roles.manage"),
  MANAGER: [
    "company.read",
    "users.read",
    "crm.read",
    "crm.create",
    "crm.update",
    "sales.read",
    "sales.create",
    "invoice.read",
    "stock.read",
    "finance.read",
    "hr.read",
    "projects.read",
    "projects.manage",
    "ai.use",
    "reports.read",
  ],
  SALES: ["crm.read", "crm.create", "crm.update", "sales.read", "sales.create", "invoice.read", "ai.use"],
  ACCOUNTING: ["invoice.read", "invoice.create", "invoice.validate", "invoice.cancel", "finance.read", "finance.export", "reports.read"],
  INVENTORY: ["stock.read", "stock.adjust", "stock.transfer", "reports.read"],
  HR: ["hr.read", "hr.manage", "users.read", "reports.read"],
  EMPLOYEE: ["crm.read", "sales.read", "stock.read", "projects.read", "ai.use"],
  VIEWER: ["company.read", "crm.read", "sales.read", "invoice.read", "stock.read", "reports.read"],
};
